### ISSUE TITLE
Enhancing User Experience with Dark Mode Feature

### ISSUE THREAD

**Issue by Prachirsh** [imadityayadav/frontend#28]
I would like to propose the addition of a dark mode feature to your website. This feature allows users to switch between light and dark themes based on their preference, improving accessibility and reducing eye strain during different lighting conditions. I'll implement it using a CSS class for styling, along with a toggle button that allows users to switch seamlessly between the two modes.
I have implemented this feature before for another project. Can you assign it to me?

**Comment by imadityayadav** [comment]
@Prachirsh Done

**Comment by Prachirsh** [comment]
Done means you are assigning this task to me?
