### ISSUE TITLE
Improve look of item cards and add favicon [HACKTOBERFEST]

### ISSUE THREAD

**Issue by gurdittcancode** [imadityayadav/frontend#41]
Hi, I was going through the website and I thought that the product cards look a bit plain and I have some ideas to make them look better. Can you please assign this issue to me so that I can start working on it?
Cheers, Gurditt

**Comment by unclebinary1001** [comment]
hi I would like to work on this, thanks!

**Comment by gurdittcancode** [comment]
@unclebinary1001 hey, i raised this issue, please respect that and find some other issue to contribute to. thanks :)

**Comment by unclebinary1001** [comment]
Sorry about that. I hadn't properly read the issue that it was self-assigned. Happy coding on this 😃.

**Comment by gurdittcancode** [comment]
sorry if my message seemed harsh, that was not my intention. best, gurditt

**Comment by gurdittcancode** [comment]
@imadityayadav can you please assign it to me? I'd love to work on this
