### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by stephikebudu** [imadityayadav/frontend#94]
I plan to add the brand logo as the e-commerce store's favicon to improve UX when user has multiple tabs open
@imadityayadav please assign it to me

**Comment by imadityayadav** [comment]
> @imadityayadav 
> 
> ![image](https://github.com/user-attachments/assets/7365ea04-a130-41dd-9b53-b013a8f001c9)
> 
> what about this favicon i ll remove the background of it or you can found some more or u can tell me about which one u will like
> 
> 
> 
> 

Okay make the PR
